### ISSUE TITLE
File for translation

### ISSUE THREAD

**Issue by frain45** [SchumacherFM/Magento-CmsRestriction#3]
If you can add in the module the directory structure for translations + the language file with strings, I can provide the Italian translation.

Alessandro

**Comment by frain45** [comment]
I have prepared the Italian translation and tested it. How can I give you the file? 
It is not possible to upload a CSV here and notifications from Github hide your email address.

Unfortunately I am not skilled with Github!

**Comment by SchumacherFM** [comment]
Just paste it here as a comment :-)

**Comment by frain45** [comment]
Ok, pasting below file SchumacherFM_CmsRestriction.csv:

"CMS Restrictions","Limitazioni CMS"
"URL Page Access denied","URL pagina di accesso negato"
"If a customer is logged in and wants to access a restricted page he/she will be redirected to that page.","Se un utente dopo l'accesso cerca di vedere una pagina riservata, verr&agrave; inviato a questa pagina"
"Restrict to customer groups or individual customers","Limita ad alcuni specifici gruppi o utenti"
"Allow Customer Groups","Consenti gruppi di utenti"
"Allow Customer IDs","Consenti alcuni ID utente"
"Comma separated list with numbers.","Lista di numeri separati da virgole"
"CMS Restriction","Limitazione CMS"

**Comment by frain45** [comment]
Ok, I have pasted the text in a comment.
Github says "reply directly" so trying to send it attached as well.

Thanks for all your support!

Cyrill Schumacher ha scritto il 09/12/2013 2.23:

**Comment by SchumacherFM** [comment]
Thanks! Translations has been added
