### ISSUE TITLE
Restrictions not updating

### ISSUE THREAD

**Issue by goose1984** [SchumacherFM/Magento-CmsRestriction#4]
It would seem as though updateCmsRestriction in the Observer is not updating with the correct values

**Comment by SchumacherFM** [comment]
What? How to reproduce?

**Comment by Daniel-NCR** [comment]
We are having an issue where after selecting multiple customer groups for the CMS restrictions, the values will not remain saved after saving the form. You are able to reproduce by importing the attached list of customer groups.
[CustomerGroups.txt](https://github.com/SchumacherFM/Magento-CmsRestriction/files/146807/CustomerGroups.txt)

**Comment by ajpirciovs** [comment]
@goose1984 You might be having an issue that's preventing them from saving properly, I put in a pull request which you can find here, hopefully fixes your problem: https://github.com/SchumacherFM/Magento-CmsRestriction/pull/8

**Comment by SchumacherFM** [comment]
PR #8 will fix this issue
