### ISSUE TITLE
Values will not save

### ISSUE THREAD

**Issue by Daniel-NCR** [SchumacherFM/Magento-CmsRestriction#5]
We are having an issue where after selecting multiple customer groups for the CMS restrictions, the values will not remain saved after saving the form. You are able to reproduce by importing the attached list of customer groups.
[CustomerGroups.txt](https://github.com/SchumacherFM/Magento-CmsRestriction/files/146808/CustomerGroups.txt)

**Comment by SchumacherFM** [comment]
Can you send a PR (Pull Request) to fix this issue?

https://help.github.com/articles/using-pull-requests/

**Comment by Daniel-NCR** [comment]
This PR has been created. Hopefully this is a quick fix and you can provide a resolution.

Thank you,

Daniel Rubenstein

**Comment by SchumacherFM** [comment]
Daniel, I expressed myself incorrect. Sorry. I closed the PR. 

I mean can you, or another developer you know, send the fix?

**Comment by Daniel-NCR** [comment]
Oh! I’m not a developer. I just know enough to be dangerous.
I’m not sure what the fix would be and I don’t have access to a developer that could work on this.

I’m not 100% sure of the cause of the problem, I can just provide my insights and observations.

**Comment by ajpirciovs** [comment]
@Daniel-NCR you might need to clear your cache for it to work. I noticed the form showing up before the appropriate script was run that makes it possible to save this info. Once I did that and reloaded values with save. You also might be having an issue that's preventing them from saving properly, I put in a pull request which you can find here, hopefully fixes your problem: https://github.com/SchumacherFM/Magento-CmsRestriction/pull/8

**Comment by SchumacherFM** [comment]
PR #8 will fix this issue
